# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npx babel-node ex_01/training01.js
    - run: npx babel-node ex_01/training02.js
    - run: npx babel-node ex_01/training03.js
    - run: npx babel-node ex_01/training04.js
    - run: npx babel-node ex_01/training05.js
    - run: npx babel-node ex_01/training06.js
    - run: npx babel-node ex_01/training07.js
    - run: npx babel-node ex_02/training01.js
    - run: npx babel-node ex_02/training02.js
    - run: npx babel-node ex_02/training03.js
    - run: npx babel-node ex_02/training04.js
    - run: npx babel-node ex_02/training05.js
    - run: npx babel-node ex_02/training06.js
    - run: npx babel-node ex_02/training07.js
